### ISSUE TITLE
Want a way to have custom logic based on other values in my schema

### ISSUE THREAD

**Issue by ziyak97** [fabian-hiller/valibot#120]
An example would be

```
  privacyPolicyUrl: string([
    (input, context) => {
      if (!context.isPrivacyPolicyAvailable && !input) {
        return {
          issue: {
            validation: "custom",
            message: "Privacy Policy URL is required",
            input,
          },
        };
      }
      return { output: input };
    },
    url("Please enter a valid URL"),
  ]),
```

i am not sure if something like this already exists any suggestions would be appreciated

**Comment by fabian-hiller** [comment]
Hey, thanks for creating this discussion. Please read through the following three issues and discussions and let me know if your questions are answered. Otherwise, I can try to address your specific use case.

- https://github.com/fabian-hiller/valibot/issues/5
- https://github.com/fabian-hiller/valibot/issues/76
- https://github.com/fabian-hiller/valibot/discussions/109

**Comment by ziyak97** [comment]
hey thanks for the prompt reply. sadly these don't work for my usecase as these checks happen post the initial schema check. 

my usecase is for someone to enter their privacy policy url which needs to be validated as a url. if they however check a box lets say a boolean of noPrivacyPolicy, then the privacy policy url is no longer required. instead they would have to enter a reason as to why they would not put the same which would now be required (it would be optional if noPrivacyPolicy was not selected). there are other fields in my form also so ideally i would NOT want my privacy policy related validations to happen only after those other validations go through successfully.

**Comment by fabian-hiller** [comment]
You can build that with `union`.
