### ISSUE TITLE
Create parser for integrations with tRPC etc

### ISSUE THREAD

**Issue by KATT** [fabian-hiller/valibot#159]
> Picking up this conversation from the PR here https://github.com/trpc/trpc/pull/4793#issuecomment-1716854579 in regards to tRPC integration
> 
> @juliusmarminge if Valibot provides a special function for tRPC as a compatibility layer, what do you think would be the best name for it? Below are a few examples:
> 
> ```ts
> import { object, string } from "valibot";
> import { … } from "valibot/trpc";
> 
> const schema = object({ key: string() });
> 
> .input(parse(schema))    // parse
> .input(wrap(schema))     // wrap
> .input(use(schema))      // use
> .input(with(schema))     // with
> .input(valibot(schema))  // valibot
> .input(as(schema))       // as
> .input(fits(schema))     // fits
> .input(is(schema))       // is
> .input(adapter(schema))  // adapter
> .input(trpc(schema))     // trpc
> ```

---

I think a good implementation would be

**Create parser:**

```ts
import { object, string } from "valibot";
import { createParser } from "valibot";

const schema = object({ key: string() });
const objectParser = createParser(schema);
```

**With tRPC**

```ts
.input(createParser(schema))
```

**Without tRPC**

```ts
const parseObj = createParser(
    object({
        key: string(),
    })
);

parseObj({ key:' ..' });
```

> Should be functionally equivalent of doing `_.curry(parse, schema)`

**Potential additions**

- Add a `createSafeParser`-function
- Make `Output`/`Input` work with the parser too
- As mentioned before, it'd be nice to not need this at all and just be able to do e.g. `object({ key: string() }).parse(...)` but I understand you want to keep the build minimal

**Comment by fabian-hiller** [comment]
For people who have not been involved before, I would like to give some context to this issue.

Initially, Valibot used try/catch for error handling. However, we changed this for performance reasons. This change made the integration with tRPC a bit more cumbersome. tRPC requires an error to be thrown at the end of the validation, instead Valibot now returns an object with the output or issues.

Since Valibot uses a modular design to keep the size of each bundle to a minimum, a schema no longer includes this functionality. Instead, this functionality is included in our `parse` method. This results in us having to add this functionality internally or externally to a Valibot schema when used with tRPC.

An example of this is shown above. A function such as `createParser` could be used to add the functionality to a schema so that it is compatible with tRPC.

**Comment by jgoux** [comment]
Hello all 👋,

Wouldn't having a curried version of `parse` (in addition to the current behavior) be the solution?

Here is a playground: https://tsplay.dev/mqyR2m

**Comment by fabian-hiller** [comment]
Yes for tRPC this would be perfect. However, we would then have two different ways `parse` can be used and that makes using a library a bit confusing in my opinion. I will think about this.

**Comment by Songkeys** [comment]
> Initially, Valibot used try/catch for error handling. However, we changed this for performance reasons.

@fabian-hiller Could you be more specifically so that we won't be tricked by this in the future? How was the performance influenced by the try/catch statements?

**Comment by fabian-hiller** [comment]
@Songkeys have a look at page 39 in my thesis: https://valibot.dev/thesis.pdf

**Comment by fabian-hiller** [comment]
This issue should be solved by our new `parser` and `safeParser` API.
