### ISSUE TITLE
Doc update

### ISSUE THREAD

**Issue by MariuzM** [fabian-hiller/valibot#186]
Recent changes just to update doc's but was not sure how you want PR to be done so raising here.

`website/src/routes/guides/(main-concepts)/pipelines/index.mdx`

```tsx
const StringSchema = string([
  (input) => {
    if (input.length > 10) {
      return getPipeIssues('custom', 'Invalid length', input);
    }
    return getOutput(input);
  },
]);
```

<img width="1097" alt="image" src="https://github.com/fabian-hiller/valibot/assets/36937039/34aab653-991c-4760-a665-df88b6521013">

**Comment by fabian-hiller** [comment]
Ahh... thank you! Yes, we should update it to [this](https://github.com/fabian-hiller/valibot/releases/tag/v0.16.0). If you are interested, you can create a PR. Otherwise I will make the improvement.

**Comment by MariuzM** [comment]
@fabian-hiller are you sure you want as per link or maybe like this? 

```tsx
const StringSchema = string([
  (input) => {
    return input.length > 10
      ? getPipeIssues('custom', 'Invalid length', input)
      : getOutput(input);
  },
]);
```

Also sorry silly question but Im used to creating branches and then making PR to main from them but cant in this case, what is the usual workflow here?

**Comment by fabian-hiller** [comment]
Maybe it is better for the docs to take the verbose variant, so that the code is more understandable for beginners. What do you think?

```ts
import { getOutput, getPipeIssues, string } from 'valibot'; // 0.54 kB

const StringSchema = string([
  (input) => {
    if (input.length > 10) {
      return getPipeIssues('custom', 'Invalid length', input);
    }
    return getOutput(input);
  },
]);
```

You need to create a fork of the library ([there](https://github.com/fabian-hiller/valibot) is a button on the top right) and make the change in it. Then GitHub will show you the option to create a PR in your fork on its website. If this is too cumbersome, I can just make the change.

**Comment by MariuzM** [comment]
Agree also its easier to later add more if statements
