### ISSUE TITLE
Validation Incorrectly Passed Despite Error in `custom/customAsync`

### ISSUE THREAD

**Issue by mathieumetral** [fabian-hiller/valibot#188]
Hello,

Currently, when utilizing the custom or customAsync function within the data validation schema, it appears that despite an error being thrown, the validation is considered successful. Below is a code snippet that reproduces the issue:

```
const DataSchema = objectAsync(
  {
    firstName: string(ValidationIssueCode.INVALID_TYPE),
    lastName: nullish(string(ValidationIssueCode.INVALID_TYPE)),
    email: stringAsync(ValidationIssueCode.INVALID_TYPE, [
      email(ValidationIssueCode.INVALID_VALUE),
      customAsync(async input => {
        throw new Error('Some error');
      }),
    ]),
  }
);
```

In this code snippet, an error is thrown within the `customAsync` function for the email field. However, the validation is still considered successful, which is not the expected behavior, I think.

It is unclear whether this is a bug or a misunderstanding in the implementation. Any guidance or fix for this issue would be greatly appreciated.

Thank's !

**Comment by fabian-hiller** [comment]
There is no try/catch logic inside Valibot that can catch this kind of errors. Theoretically, we could add this functionality to [`custom`](https://github.com/fabian-hiller/valibot/blob/v0.17.1/library/src/validations/custom/custom.ts) and [`customAsync`](https://github.com/fabian-hiller/valibot/blob/v0.17.1/library/src/validations/custom/customAsync.ts).

Currently, both implementations are designed to make the function you pass as the first argument a requirement. This means that we execute this function inside an if statement and depending on whether `true` or `false` is returned, the validation is done. In simple words: If the condition of your function is `true`, the data is valid. Otherwise, an error is returned.

Since this is a modular library, you can also just replace [`customAsync`](https://github.com/fabian-hiller/valibot/blob/v0.17.1/library/src/validations/custom/customAsync.ts) with your own implementation that does the validation depending on try/catch. Similar to what we are currently doing with [`url`](https://github.com/fabian-hiller/valibot/blob/v0.17.1/library/src/validations/url/url.ts).

**Comment by mathieumetral** [comment]
Thanks Fabian! If you are ok with the idea of ​​adding the error catch and thus considering the validation as failed in `custom` and `customAsync`, I can release the PR. Otherwise, I'll make my own implementation.

**Comment by fabian-hiller** [comment]
Yes, feel free to create a PR. I am not sure yet, but I think this functionality makes sense and is useful.
