### ISSUE TITLE
Any plan to improve performance?

### ISSUE THREAD

**Issue by southorange0929** [fabian-hiller/valibot#19]
I write a simple benchmark with real case. 
- zod
- yup
- joi
- valibot

```ts
import Benchmark from "benchmark";

import { z } from "zod";
import * as yup from "yup";
import Joi from "joi";
import * as valibot from "valibot";

const SUITE_NAME = "";
const suite = new Benchmark.Suite("Validate Benchmark");

const value = {
  latitude: 10,
  longitude: 10,
  scale: 10,
  name: "",
  address: "",
  powerLevel: "low",
};

const stringSchema = z.object({
  latitude: z.number(),
  longitude: z.number(),
  scale: z.number().min(5).max(18),
  name: z.string().optional(),
  address: z.string().optional(),
  powerLevel: z.enum(["low", "medium", "high"]),
});

const yupSchema = yup.object({
  latitude: yup.number(),
  longitude: yup.number(),
  scale: yup.number().min(5).max(18),
  name: yup.string().optional(),
  address: yup.string().optional(),
  powerLevel: yup.mixed().oneOf(["low", "medium", "high"]),
});

const joiSchema = Joi.object({
  latitude: Joi.number(),
  longitude: Joi.number(),
  scale: Joi.number().min(5).max(18),
  name: Joi.string().optional(),
  address: Joi.string().optional(),
  powerLevel: Joi.string().valid("low", "medium", "high"),
});

const valibotSchema = valibot.object({
  latitude: valibot.number(),
  longitude: valibot.number(),
  scale: valibot.number([valibot.minRange(5), valibot.maxRange(18)]),
  name: valibot.optional(valibot.string()),
  address: valibot.optional(valibot.string()),
  powerLevel: valibot.enumType(["low", "medium", "high"]),
});

suite
  .add("zod validate", () => {
    stringSchema.safeParse(value);
  })
  .add("yup validate", () => {
    yupSchema.validate(value);
  })
  .add("joi validate", () => {
    joiSchema.validate(value);
  })
  .add("valibot validate", () => {
    valibot.safeParse(valibotSchema, value);
  })
  .on("cycle", (e: Benchmark.Event) => {
    console.log(`${SUITE_NAME}: ${e.target}`);
  })
  .on("complete", function () {
    console.log("Fastest is " + this.filter("fastest").map("name"));
    process.exit(0);
  })
  .run();

```

<img width="495" alt="image" src="https://github.com/fabian-hiller/valibot/assets/32590310/9592a193-7cb0-4985-944a-211bad2fba33">

`Zod` is so fast, is my case not good or any plan to improve performance?

**Comment by fabian-hiller** [comment]
I have already done some performance tests in advance. What exactly does your benchmark examine? If data is only validated iteratively, for example in a loop, this benchmark only shows how well V8 can optimize this process. However, this does not necessarily have anything to do with performance in the real world. Is there a use case where a schema is executed a million times synchronously?

For example, Valibot is probably the fastest when it comes to initializing a schema. In a benchmark that uses a loop to validate data against a schema millions of times, Valibot performs worse than Zod. This is because Valibot is currently implemented in such a way that the individual functions that make up Schema are executed during validation.

Zod, on the other hand, collects all validation-related information when initializing a schema and executes few large functions when validating a type. Although Valibot probably executes less code overall than Zod when validating, Zod performs better in a benchmark with a loop because V8 can optimize a few large functions better than many small ones.

However, this also means that Valibot is probably faster than Zod in the real world and Zod only performs better in extreme situations. In the next few weeks, I will conduct further research to see if my assumptions are correct and can be proven.

**Comment by southorange0929** [comment]
Thanks for your reply.
You're right,and it's so amazing that bundle size so small.Looking forward to your results.

**Comment by fabian-hiller** [comment]
I'll be sharing my research in about a month.

**Comment by yamiteru** [comment]
Benchmarks can be very tricky, especially in JS since we have to factor in the fact that JS engines do speculative optimizations in the background.

So to make things as fair as possible I'd do different number of runs (10 - worst case, 1000 - normal case, 10000 - most likely fully optimized by JS engine by now) for each type of benchmark + do each type of benchmark with varying size of input (if possible).

So this is how the structure would look like:

- Object
  - 5 keys
    - 10 runs
      - Valibot
      - Zod
      - ...
    - 1000 runs
      - ...
    - ...
  - 20 keys
  - ...
- ... 

This way you can know strong and weak parts of each library in much more detail than if you were to do it the usual way which is to select one size and one number of iterations. Some libs might be better with smaller or bigger inputs and some might get fully optimized sooner and some later. There's a lot of variables at play at determining what "fast" actually means.

**Comment by yamiteru** [comment]
Oh and I also highly recommend benchmarking memory usage since it's also a very important metric.

**Comment by fabian-hiller** [comment]
@yamiteru do you know any tools that you can recommend for the benchmarks?

**Comment by yamiteru** [comment]
Unfortunately no and that's why I'm building my own which check all those boxes. However the hardest part proved to be math and statistics. So it's current on hold until I figure out the best algos to determine things like change points, stabilization periods, etc.

**Comment by naruaway** [comment]
I found that reducing the usage of object spread operators greatly improves the runtime performance and confirmed that in my environment Valibot gets faster than Zod using @southorange0929's benchmark.

Could you help testing / playing with https://github.com/fabian-hiller/valibot/pull/46 ?

Note that I also tested https://github.com/moltar/typescript-runtime-type-benchmarks/pull/1112 👍 

I really like the design of Valibot and I strongly believe Valibot can be faster than Zod since the implementation is much simpler.

**Comment by fabian-hiller** [comment]
@stychu we will try to change this in the coming days.

**Comment by fabian-hiller** [comment]
Valibot v0.13.0 with extreme performance improvements is now available! 🔥

**Comment by stychu** [comment]
Nice. Now I have the reason to switch from zod. 3x the performance <3

**Comment by fabian-hiller** [comment]
I assume that this issue has been resolved. If not, let me know.
