### ISSUE TITLE
Custom issue formatting: how to determine expected parameters of validations

### ISSUE THREAD

**Issue by lo1tuma** [fabian-hiller/valibot#191]
Let’s say I have the following schema:

```ts
const schema = string([minLength(3)]);`
```

I want to implement a custom formatter, that would output the following error message I case the validation fails:

```ts
const result = safeParse(schema, 'a');
console.log(myFormatter(result.issues)); // Expected string to have at least 3 character(s) but instead got 1
```

While the `input` data is available and I can easily get the length of the input, it seems like there is no way to get the expected amount of characters from the `Issue`. Or am I missing something?

**Comment by fabian-hiller** [comment]
Yes, that is correct. This information is not included. We could add the optional property `requirement` to an issue which contains this information.

**Comment by lo1tuma** [comment]
Sounds like a good idea. Would it be a `string` or would the type of `requirement` depend on what `validation` is? So in case of `min_length` it would be a `number` and for `includes` it would be `string`.

**Comment by fabian-hiller** [comment]
I think we need to declare them as `any` or `unknown` because the requirement can be anything. For example, with `custom` it can be a function. We should investigate if there is a way to make it type safe in the long run.

**Comment by lo1tuma** [comment]
In this case I would prefer to make it `unknown`, since I try to avoid using `any` completely. Another idea would be to make it at least type safe for the builtin validations and only `unknown` in case of `custom` validations. So that the `validation` property acts as a discriminator, so I can be sure that when I check `issue.validation === 'min_length'` that `requirement` will be always a number.

**Comment by fabian-hiller** [comment]
Yes, as soon as I find the time, I will take a look at it.

**Comment by lo1tuma** [comment]
I’ve looked a little bit into this. I would love to get this feature type safe, but I think one issue is that on `Issue` the `validation` property is defined as `string` and that custom validation functions can put any value in there. I order to use `validation` as a discriminator for the new `requirement` we would need to change it to union type of string literals. But I guess this would be a breaking change. And then the question is how do we handle it for custom validations? I though about using a template string literal type, so that we could enforce e.g. a strict prefix (e.g. `custom_${string}`), but this still doesn’t give us a type safe `requirement` for custom validations 🤔.

**Comment by fabian-hiller** [comment]
Thanks for your research! Unfortunately, I don't have a solution for this either. Breaking changes are ok as long as we are still in v0. Being able to write your own validation functions and name them in issues seems important to me for Valibot.

By the way, I am toying with the idea of changing the return value of the transformation and validation functions. Instead of a function it might make sense to return an object with a `._parse` method. This would make the structure similar to the schemas and we could add information like `requirement` to the object so that this information is accessible.

For example, this could allow us to retrieve information to generate validation attributes such as `pattern` or `min` and `max` for `<input />` fields.

**Comment by Saeris** [comment]
I don't particularly think a change to returning an object with an internal method is particularly better than just assigning metadata properties to the returned function using `Object.assign()`, as I've done in #211 

The way I see it, changing the return type to an object instead of a function would just necessitate refactoring a lot of unit tests for not much for a value add.

**Comment by fabian-hiller** [comment]
For me, it is more important to have a good and consistent structure in the long run. For that I am willing to go a more cumbersome way. Nevertheless, the idea with `Object.assign()` is not bad. I'm only bothered by the fact that we now have two different formats, and `Object.assign()` is also a bit cumbersome and difficult to understand for beginners when creating their own validation functions.

**Comment by Saeris** [comment]
In #211 I added a `checks` property to each schema type which accepts a Pipe, which returns metadata about each of the validations that were passed to the schema. Here is an example of what a string schema returns:

```ts
const schema = string([minLength(2), maxLength(3)])
// schema.checks => [
//   { kind: 'min_length', requirement: 2, message: 'Invalid length' },
//   { kind: 'max_length', requirement: 3, message: 'Invalid length' },
// ]
```

For a more complicated schema, like a nested object, here's what you could work with:

```ts
const schema = object({
  simple: string(),
  validated: number([maxValue(5)]),
  nested: object({
    foo: literal(`foo`),
    bar: union([literal(`baz`), literal(`qux`)]),
  }),
});
// schema.object = { 
//  simple: {
//    schema: 'string',
//    async: false,
//    checks: []
//  },
//  validated: {
//    schema: 'number',
//    async: false,
//    checks: [
//      { kind: 'max_value', requirement: 5, message: 'Invalid value' }
//    ]
//  },
//  nested: {
//    schema: 'object',
//    object: {
//      foo: {
//        schema: 'literal',
//        literal: 'foo',
//        async: false
//      },
//      bar: {
//        schema: 'union',
//        union: [
//          { schema: 'literal', literal: 'baz', async: false },
//          { schema: 'literal', literal: 'qux', async: false }
//        ],
//        async: false
//      },
//      async: false,
//      checks: []
//   }
// }
```

I think with this data you can reasonably determine all the validation parameters you need.

---

As for `Object.assign()` being a little unintuitive, it's less of a pain than the following:

```ts
const validator = (input) => { /* ... */ }
validator.kind = `hexcode`
validator.requirement = new RegExp(/* ... */)
validator.mesage = `Invalid hexcode!`
```

This is because TypeScript would raise an error saying that each of those properties don't exist on `validator`, but in the case of `Object.assign()` it's both perfectly happy to accept any key/value pair AND it correctly figures out the type information for the overall function at the same time.

**Comment by fabian-hiller** [comment]
Thank you for the info. Let's move this discussion to PR #211. I will answer you there.

**Comment by fabian-hiller** [comment]
I just want to let you know that I will consider this issue and plan to find a solution before v1. The optimal solution would be a discriminated union based on the `validation` property. However, it should still be possible to extend Valibot with custom schema and validation functions.

The same applies to `BaseSchema` and `BaseValidation`. Here, too, we could improve type safety by creating the types `Schema` and `Validation` using a discriminated union. I had already tried this in the past, but ran into problems. However, I believe that these can be solved.

Since I want to combine Valibot and [`decode-formdata`](https://github.com/fabian-hiller/decode-formdata) in December and in January will rework the integration in Modular Forms, I expect to learn a lot about what is important for library authors and developers in this process.
