### ISSUE TITLE
Type 'T' cannot be used to index type` when trying to access value by key

### ISSUE THREAD

**Issue by laneme** [fabian-hiller/valibot#239]
I'm not sure how to title this better but this is what i'm trying to achive

```ts
const _originalSchema = object({
	path: string(),
	xy: number(), 
})

function helper<T extends keyof Output<typeof _originalSchema>>(key: T) {
	// narrow the schema
	const schema = pick(_originalSchema, [key])
	const parsed = parse(schema, { [key]: `SOME_VALUE_TO_BE_VALIDATED` })

	// error
	return parsed[key]
} 
```
The error looks someth like this

```ts
Type 'T' cannot be used to index type '{ [k in keyof WithQuestionMarks<{ [TKey in keyof Pick<{ path: StringSchema<string>; xy: NumberSchema<number>; }, T>]: Output<Pick<{ path: StringSchema<string>; xy: NumberSchema<number>; }, T>[TKey]>; }>]: WithQuestionMarks<...>[k]; }'.ts(2536)
```

If I don't narrow the schema and simply write it like this, it works correctly
```ts
function helper<T extends keyof Output<typeof _originalSchema>>(key: T) {
	const data = { [key]: `SOME_VALUE_TO_BE_VALIDATED` }

	return parse(_originalSchema.entries[key], data)
}

helper('xy') // number
```
Thank you for the awesome lib by the way.

```sh
typescript: v5.2.2
valibot: v0.20.1
```

**Comment by fabian-hiller** [comment]
Unfortunately I did not find a solution quickly. The problem seems to be that `T extends keyof ...` is not a concrete type and `pick` can't handle it to produce a proper output type signature. Also, I don't know if this is generally possible with TypeScript, since you can change `key` at any time before using the argument with `parsed`. If you can't find a solution yourself, try asking on the TypeScript Discord. In the meantime, you can use the following workaround.

```ts
parsed[key as keyof typeof parsed]
```

**Comment by laneme** [comment]
Thank you for the nice workaround.
I'll dig it a lil bit more and see if I can get to the bottom of it.

**Comment by fabian-hiller** [comment]
Do you have any news on this issue?
