### ISSUE TITLE
`undefined` and `unkown` are marked as optional

### ISSUE THREAD

**Issue by emilgpa** [fabian-hiller/valibot#242]
For example, with the follow schema:

```ts
export const mySchema = object({
    value: unknown(),
    checked: boolean(),
})
```

`valibot` returns as:

```ts
const mySchema: ObjectSchema<{
    value: UnknownSchema<unknown>;
    checked: BooleanSchema<boolean>;
}, undefined, {
    checked: boolean;
    value?: unknown;
}>
```

and 

```ts
type H = Output<typeof mySchema>
``` 

is equal to 

```ts
type H = {
    checked: boolean;
    value?: unknown;
}
```

but it should be:

```ts
type H = {
    checked: boolean;
    value: unknown;
}
```

**Comment by fabian-hiller** [comment]
Thanks a lot for creating this issue. I will fix that as soon as possible.

**Comment by fabian-hiller** [comment]
I have now investigated the problem. Zod behaves the same way as Valibot, and theoretically it is not completely wrong, since `any` and `unknown` also include `undefined`. However, it would be better if entries were only marked as optional with a question mark when using `optional` because there is of course an difference between an `undefined` and optional entry. I will investigate this further.

**Comment by fabian-hiller** [comment]
Should I mark a field as optional only if [`optional`](https://github.com/fabian-hiller/valibot/blob/main/library/src/schemas/optional/optional.ts) is used or also with [`nullish`](https://github.com/fabian-hiller/valibot/blob/main/library/src/schemas/nullish/nullish.ts)?

**Comment by emilgpa** [comment]
In my opinion, it should be only if `optional` is used. The other one, `nullish`, I would leave only to mark the field as null or undefined

**Comment by fabian-hiller** [comment]
This issue will be solved in the next version of Valibot.

**Comment by fabian-hiller** [comment]
v0.23.0 is now available.
