### ISSUE TITLE
flatten returns an odd type

### ISSUE THREAD

**Issue by sacrosanctic** [fabian-hiller/valibot#319]
### describe the problem

```js
import { flatten, object, safeParse, string } from 'valibot'

const schema = object({ a:string() })

const result = safeParse(schema, {})
const errors = flatten(result.issues).nested
```
errors has a type of `Partial<Record<string, [string, ...string[]]>>`

Two parts look odd to me
- `Partial`
- `[string, ...string[]]`

### expected

`Record<string,string[]>`

**Comment by fabian-hiller** [comment]
No, the typing should be correct. `partial` is required because not every entry must have an error. `[string, ...string[]]` is better than `string[]` because if there is an error, you can access the first error with `key[0]` in a type-safe way. The other behaviour is the same as for `string[]`. Feel free to reach out if you have any further questions or feedback.

You can pass your schema as a generic to make `flatten` type safe.

```ts
import * as v from 'valibot';

const Schema = v.object({ key1: v.string(), key2: v.number() });

try {
  const output = v.parse(Schema, { key1: 'hello', key2: 123 }); // `output` is type-safe
} catch (error) {
  const errors = v.flatten<typeof Schema>(error); // `errors` is also type-safe
}
```

**Comment by sacrosanctic** [comment]
Thank you for explaining.
