### ISSUE TITLE
Fallback value is not sent through the pipeline and can lead to unexpected behaviors

### ISSUE THREAD

**Issue by sqmasep** [fabian-hiller/valibot#334]
I want to get your opinions about that problem: should fallback values run through pipelines?

Fallback values are "only" type-safe, but for more complex types with special formats (e.g: email) it skips the pipeline validation of the schema. It can be unsafe and dangerous in some scenarios.

See example below

```ts
const EmailSchema = fallback(string([email()]), "not an email!");

// Expectable behavior, it's perfectly fine
const res = parse(EmailSchema, "a@gmail.com");

// WARN! The input doesn't match the schema, but the fallback value skipped the pipeline and is considered correct
const res2 = parse(EmailSchema, 42); // => "not an email!"
```

I don't know if zod has the same problem, I haven't used it for a while and not enough to know if that's even possible

**Comment by fabian-hiller** [comment]
I took a look at Zod. Zod does the same thing as Valibot and just replaces the input with the given fallback value on error. I think both ways are fine, but we need to document them carefully to avoid unexpected behavior.

Option 1: We leave it as it is and give the responsibility to the developer to make sure that the passed value is valid.
Option 2: We run the pipeline with the provided fallback value and return an issue if it is invalid.

**Comment by fabian-hiller** [comment]
I have just looked again at the implementation of `optional`, `nullable` and `nullish` and compared it with that of `fallback`. There is a significant difference that we should probably document.

The default value of `optional`, `nullable` and `nullish` is an input value that replaces the actual input value if it is `null` or `undefined`. In contrast, for `fallback` it is an output value that replaces the output if an issue was found. I think this behavior is correct and expected.

Here is an example that expects a string as input and a number as output.

```ts
import * as v from 'valibot';

const Schema1 = v.nullable(
  v.transform(v.string(), (value) => value.length),
  'default' // string
);

const Schema2 = v.fallback(
  v.transform(v.string(), (value) => value.length),
  7 // number
);
```

Since `fallback` is an output value. It is not technically possible to send this as an input through the provided schema and pipeline. Therefore option 2 of my previous comment is not an option.

**Comment by sqmasep** [comment]
Nice catch! It's a good explanation and is much clearer now. Thank you, I can close the issue now 😉
