### ISSUE TITLE
Links on valibot.dev does not work

### ISSUE THREAD

**Issue by homburg** [fabian-hiller/valibot#44]
Hello

I tried reading the documentation on valibot.dev, but nothing happens when I click on the "Guides" and "API Reference" links.

## Browser

```
Google Chrome | 115.0.5790.114 (Official Build) (arm64)
-- | --
Revision | 67277e15806bf7f0307b37cd6f8f29e71b615796-refs/branch-heads/5790_90@{#25}
OS | macOS Version 13.5 (Build 22G74)
JavaScript | V8 11.5.150.16
User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
```

## Demo video

https://github.com/fabian-hiller/valibot/assets/235886/e2c57a63-69af-49ed-808c-05d8d629fdc9

**Comment by fabian-hiller** [comment]
Interesting. Everything works fine for me. Can you test it on another device or browser?

**Comment by homburg** [comment]
Screenshots had some error logs hidden. Uploadet a demo video instead.

Will test in other browser/device @fabian-hiller

**Comment by homburg** [comment]
Same behaviour/errors in safari on the same computer @fabian-hiller

**Comment by homburg** [comment]
Works on chrome mobile on my Samsung S21 phone on same network

**Comment by homburg** [comment]
Getting this error on https://valibot.dev/manifest.json

![image](https://github.com/fabian-hiller/valibot/assets/235886/f645368f-56fb-45e7-92f4-36911b0e17e3)

**Comment by homburg** [comment]
Same behavior on a coworkers machine in the same office

**Comment by fabian-hiller** [comment]
The problem seems to be that the HTML can be downloaded, which already contains everything important to display the website, but it does not work to load additional resources that are required for interactions. Could it be related to the internet configuration e.g. firewall at your office?

As a workaround you can disable JavaScript for the Valibot website, then everything should work normally.

**Comment by homburg** [comment]
Works on my home internet. So probably caused by office firewall.

**Comment by adamroyle** [comment]
@fabian-hiller I'm getting the same error - have tried Chrome on Desktop & Safari on Mobile, with two different internet providers.

**Comment by fabian-hiller** [comment]
I cannot reproduce the problem. Maybe it has something to do with the edge network of Netlify.

**Comment by adamroyle** [comment]
It seems like a proxy misconfiguration, perhaps specific to your Netlify account? Maybe reach out to their support?

Here is an example URL that is not loading:
https://valibot.dev/build/q-5b659d1a.js

Cycle Prohibited
Description: Could not process your request for the document because it would cause an HTTP proxy cycle. Please check the URL and your browser's proxy settings.

**Comment by fabian-hiller** [comment]
I have contacted Netlify. Thank you for reporting this issue!
