### ISSUE TITLE
Playground UI/UX

### ISSUE THREAD

**Issue by babakfp** [fabian-hiller/valibot#475]
Hi 👋

It would be better if the buttons (copy, delete, share, etc) were only visible when hovering over their parent box.

![Screenshot 2024-03-09 123400](https://github.com/fabian-hiller/valibot/assets/44144724/7ea42c46-4340-4e45-9dbe-ae45198110ba)

The delete button overlays on the log content which is a bit annoying.

(I can open a PR)

**Comment by fabian-hiller** [comment]
I think the buttons should be visible right away. This improves the UX in my eyes. But I understand the problem with the "delete" button. I do not have a perfect solution at the moment. As a workaround, you could just click the "execute" button twice, since the "delete" button only covers the first line.
