### ISSUE TITLE
check minLength of an array 

### ISSUE THREAD

**Issue by cannap** [fabian-hiller/valibot#50]
hi i have this 

```js
export const pollOptions = object({
  //WIP we need more
  answer: string([minLength(3)]),
  id: optional(union([string(), number()])),
  order: number()
});
...
pollOptions: array(pollOptions), 
...
```
is there are a way to check pollOptions is min 1 (2 entries) long or do i have to use custom?

thanks

**Comment by fabian-hiller** [comment]
If you want to have perfect types, I recommend to use [`tuple`](https://github.com/fabian-hiller/valibot/blob/main/library/src/schemas/tuple/tuple.ts) instead of [`array`](https://github.com/fabian-hiller/valibot/blob/main/library/src/schemas/array/array.ts). Otherwise you can also use `minLength` in the pipeline of `array`, like with the string scheme of the `answer` key.

**Comment by cannap** [comment]
will try and give feedback how i made it thanks

**Comment by cannap** [comment]
this worked but i have no idea how to use this with a tulpe its an array of object

**Comment by fabian-hiller** [comment]
```ts
// With min length 1
tuple([pollOptions], pollOptions);

// With min length 2
tuple([pollOptions, pollOptions], pollOptions);
```

**Comment by cannap** [comment]
thanks i tested but i can also have 
` pollOptions: [],` which is first empty in think with array its fine everything works  for me
