### ISSUE TITLE
feature: add branded types

### ISSUE THREAD

**Issue by zkulbeda** [fabian-hiller/valibot#56]
Introduce `brand` method
```ts
const BrandType: unique symbol = Symbol()

interface Brand<K extends string | symbol> {
  readonly [BrandType]: {
    readonly [k in K]: K
  }
}

type Branded<T, K extends string | symbol> = T & Brand<K>

function brand<TSchema extends BaseSchema, const K>(
  schema: TSchema,
  brand: K
): BaseSchema<Input<TSchema>, Branded<Output<TSchema>, K>>{
  return schema
}

const schema = brand(number([maxValue(20)]), "UserId");
parse(schema, 123) // number & Brand<"UserId">

**Comment by fabian-hiller** [comment]
Can you explain in which specific use cases `brand` is useful and offers an advantage? I have not quite understood it yet.

**Comment by fabian-hiller** [comment]
I think I understand it now. Cool idea. Once I'm done with my bachelor thesis and hopefully have some more time, I can take a closer look at it.

**Comment by fabian-hiller** [comment]
If you have time and interest, you can try to implement this feature and submit a PR. I will check your code and give you feedback.

**Comment by fabian-hiller** [comment]
The `brand` feature is now available 🎉

**Comment by danielo515** [comment]
@fabian-hiller if you have finished your degree and you are not yet familiar with thi, then you are missing one of the best type safety features. This exists in several languages with different names, but the same concept:
- ocaml: phantom types
- rust: newtype pattern 
- F# constrained types (I think) 

Since you seem to be interested in the type safety topic I really recommend taking a look at "domain modeling made functional", for some eye-opening usage examples. For me they are super valuable for IDs (what is that string? A user ID or a car ID?)

**Comment by fabian-hiller** [comment]
Thank you. I will have a look at it.
