### ISSUE TITLE
Compiled type for actions missing typing for 'requirement' in ErrorMessage

### ISSUE THREAD

**Issue by adamayres** [fabian-hiller/valibot#607]
Thanks for the great lib! I noticed that the compiled types for actions lose the typing for the `requirement` in the function callback format of `ErrorMessage`.

Repro:

https://stackblitz.com/edit/typescript-4u6iog?file=index.ts

![image](https://github.com/fabian-hiller/valibot/assets/207585/24d08376-2393-4263-8ac6-9d16a3556cce)

For example, the compiled type of `minLength` is:

```
declare function minLength<TInput extends string | any[], TRequirement extends number>(requirement: TRequirement, message?: ErrorMessage): MinLengthValidation<TInput, TRequirement>;
```

Note the typing on `ErrorMessage` lost it's generic parameters.

In the source code this type appears to be properly passed.

`minLength`

https://github.com/fabian-hiller/valibot/blob/2bdb2c8cb2228cc9d11776a60ba7e380caaece97/library/src/actions/minLength/minLength.ts#L90-L99

`ErrorMessage`

https://github.com/fabian-hiller/valibot/blob/2bdb2c8cb2228cc9d11776a60ba7e380caaece97/library/src/types/other.ts#L22-L24

`BaseIssue`

https://github.com/fabian-hiller/valibot/blob/2bdb2c8cb2228cc9d11776a60ba7e380caaece97/library/src/types/issue.ts#L55-L83

**Comment by fabian-hiller** [comment]
This should be fixed in the RC we released last week. Have a look at this [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6CBQBWfJjAAUAb3pw4A5MFIAucWGBg+8jGI5RgrAObyAlABpx6zTbsq4YNKgDu0ACY7jegZGJjBmljb2xiDmADJ8ljA88gAc9vLAqKgArnzWIgB8cAAGACr8cFB8AI5ZwJUg8fAZOgAkihnZfGKVNXUCjQC+RdYuA9YMzGwcFXzZpPCixqjI2HwACshQqIbc-IL2yqqO2kRSyKx8AAJ8AB7I4KRdLCCEtq7umd5QfkQAjABMAGYACwAVgAbAB2V70MYTFjsCCPMSkCBWSpzGDjIA).
