### ISSUE TITLE
Codemod skipping certain schema

### ISSUE THREAD

**Issue by hyunbinseo** [fabian-hiller/valibot#623]
This is the only schema that the Codemod failed to transform.

```ts
// Codemod: valibot/migrate-to-v0.31.0@0.1.0
// Original code is formatted using tabs, not spaces.

// Untouched
const RevokeUsersSchema = transform(
  SqidsArraySchema, //
  (encodedUserIds) => encodedUserIds.map((encodedUserId) => sqids.decode(encodedUserId)[0]),
);

// Expected
const RevokeUsersSchema = pipe(
  SqidsArraySchema,
  transform((encodedUserIds) =>
    encodedUserIds.map((encodedUserId) => sqids.decode(encodedUserId)[0]),
  ),
);
```

**Comment by fabian-hiller** [comment]
Actually, there are a few more cases, but my time is limited. We will try to fix the important parts in the long run. Thank you for your feedback!

**Comment by fabian-hiller** [comment]
I think it does not work because of your comment. Without it it seems to work.

**Comment by hyunbinseo** [comment]
For context, the `//` is added to format the code multi-line using Prettier.

**Comment by fabian-hiller** [comment]
We will investigate it 🫡

**Comment by HerringtonDarkholme** [comment]
Hi [ast-grep](https://github.com/ast-grep/ast-grep) author here. 👋  ast-grep is used in the underlying codemod library.

The issue here is probably because [the pattern](https://github.com/fabian-hiller/valibot/blob/main/codemod/migrate-to-v0.31.0/src/index.ts#L389) used here is sensitive to comment. 

I can give it a look to see if the pattern code can be rewritten into a more robust form.

**Comment by morgante** [comment]
Hi @hyunbinseo, did you try the [Grit version](https://docs.grit.io/registry/github.com/fabian-hiller/valibot/migrate_to_v0_31_0)? It isn't sensitive to the comment issue.

**Comment by fabian-hiller** [comment]
I will close this as the codemod seems to be less important now and I prefer to focus on our v1 release and new library features instead.
