### ISSUE TITLE
Unable to enter multiple paths to forward method

### ISSUE THREAD

**Issue by pavelrotek** [fabian-hiller/valibot#635]
Hello Fabian,

according to forward method signature one would expect, that multiple fields can be used in pathList argument. But typescript doesn't allow that. I'd expect in this case that error will be forwarded to all fields listed in pathList.

Kind regards,

Pavel

**Comment by fabian-hiller** [comment]
Please share your schema with me. You can also use our playground if you like: https://valibot.dev/playground/

**Comment by pavelrotek** [comment]
See the example. I'd expect... if forward method has array as second argument then multiple props are possible. Typescript gives the error. Multiple props works somehow, but path in returned issues is different for password2 and password1.

https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6MMDB8AFPTjiIFAFZ8mMGQG95cMGlQB3aABMAjAC5xk6TIxiOUYKwDmMgJQAacSCcAZPi4wPDIALG6eOnqohiYATJZ21rJ2Dk6unt5+Ac5BoeEe9AC+EXbY0AbIUMZyCna8agDWMlpRMVWmHq1GVbHFwgB8XSamwqNDPR7uA4QActRwqMggfIQRCgDahONmhB5b+t3GsYQAuvThDMxsHHBQfKgArqTwoinI2HwACpWostz8gi82gU2wsRBg9xgpl2kQOcUshAhHBhxUuLHYEFIfDEpAgrjuj2ebloQA

**Comment by fabian-hiller** [comment]
Is your goal to display the error message on both fields? This requires adding `forward` and `check` twice for each field

I recommend to just forward the error message to `password2` and specify in the error message that both entries do not match.

**Comment by pavelrotek** [comment]
yes, it can be... Byt my question if it is not intended to use forward with multiple fields, why the array is there..., simply one field should be enough?

**Comment by fabian-hiller** [comment]
To forward issues to deeply nested fields. Have a look at [this playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6MMDB8AFPTjiIFAFZ8mMGQG95CuKz4c+AEwBcilWo3bdugNZ8AnmYxiOUYKwDmMgJQAaHQUAX38dEICFF2xoAHdkKCM5GxdeNVsZXxEAPhwyVD4-In1DIzg+KDwoQlCbAG1CYphjQkLCewdCAF0dH3ofBmY2DjgoAwBXUnhRF1RkbD4ABXj8mW5+QULNPQMm0zgt9rNCQjgg0-7GFnYIUj4xUghvUdQJmH6gA).

**Comment by pavelrotek** [comment]
Aaaa, ok, sorry for the question. My fault. it is clear now. closing

**Comment by mariusc23** [comment]
Hi, just chiming in that I would also like to specify multiple paths. I have a requirement for a confirm password form to show the error on both fields and I haven't found a good solution.

I can't use multiple `partialCheck` because once the first one executes, the second one won't execute because one of the fields is no longer valid.

I can use `rawCheck` but then it skips the base validation (length, etc.), unless I abort pipeline early, but then it behaves more like `check` than `partialCheck`.

**Comment by fabian-hiller** [comment]
Why do you think it is better to show the error on both fields? Feel free to share a playground example using `rawCheck`.

**Comment by mariusc23** [comment]
I don't think it's better but that's what the designers want to indicate that it could have been misspelled in the first field 🙂 

Here's a playground using rawCheck:
https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAIg2QBtgAjCGQgbgCh6BjCAO1XgHkKArAUyYwAykwAWfEMjgBeTADoIvATAAUAb3pw4E5MFIAueWGBg+KjHI5RgrAOYqAlABp5OvY+ea4YNKgDu0AAmAIyGFsam5pYw1naOLhYgNgAyfHYwoioAHA6eWj6o-kEATGFyEWYWVjb2zvJJrKnpmTmeAL4ODMxsHHAi4pIyRiZmXtz8gv06Tl4WUMh+AMLiTADWKuoogYEAkoUArnwugcgwaHzwHTIAfHAaWlrA2HAqJ2eoF3IwAJ6mgQ53LwPOAsdjwGxgfbwWRvc4wOQkUiHBjAx7PFQQqHlXwBKAhOAAQmkskx8IKRTxxQB91RWlBqAgpD4clIEHshCYZCZgTggT4qGMMD4cBsiOAPPJuMCqEInSBqOQ2z2qEO6nltJA-NQyFsfEMhFEwEIM1pwJ8GUMAG11aaaabUaSTfbUas+N99ZKgsFjTb7dBgLYbPrEYcfc7UT9TPr9qxVqwIH5WGHww8Q3qRaxIWScV6neG2nnTQBdQvAjoo1FteVVrQdehy7pguBQfn7UjQ+Ta7B8AAKyCgHxUU0kLhpbgMRGQFCYAAE+AAPZDgJlyFggZOevGhIjBYoAZgALABWABsAHYNznKfrd4fTwBOH3lxj0xnM1n2Fsq9tyoA

Note how rawCheck gets called despite password1 and password2 not satisfying the minLength requirement. `abortPipeEarly` wouldn't be great here because the rawCheck error wouldn't show until the rest of the form is valid. 

Thanks for the quick response!

**Comment by fabian-hiller** [comment]
I have some tips for you. `rawCheck` allows you to call `addIssue` multiple times, which allows you to add the same (or different) issue to multiple fields. You can also use `dataset.issues` to investigate the current issues beforehand. For example, you could write `dataset.issues?.some((issue) => ...)` to check if `password1` has already failed.
