### ISSUE TITLE
Date validation default error message

### ISSUE THREAD

**Issue by HugeLetters** [fabian-hiller/valibot#654]
When receiving an invalid date(say `new Date("invalid")`) what you get as an error is
```bash
Expected Date but received Date
```
which is really confusing
I would suggest checking for invalid date case and then producing an error message like 
```bash
Expected Date but received InvalidDate
```

I'm willing to work on a PR

My current workaround is this
```ts
const DateSchema = date((issue) => {
  if (issue.input instanceof Date) {
    return 'Expected Date but received InvalidDate';
  }

  return issue.message;
})
```
Given we're already handling an error input could only be a Date if it's only an invalid date but we could do a more rigorous check here like
```ts
issue.input instanceof Date && Number.isNaN(issue.input.getTime())
```

**Comment by fabian-hiller** [comment]
Thanks for bringing this up. We could easily fix this, but we have to be careful not to break the current language-neutral `expected` and `received` system, which follows a specific syntax. Instead of English words, we use symbols like `!` and `<=` to describe both properties. Something like `InvalidDate` makes no sense because there is no `InvalidDate` data type in JavaScript. Also, `Invalid Date` does not work because it breaks our syntax. We could change it to `!Date` to produce an error message that isn't confusing, but that way it's less clear what the error actually is. I would appreciate your feedback on this.

**Comment by HugeLetters** [comment]
Would enclosing `"Invalid Date"` in quotes work? I've proposed it cause that's the way it's stringified in most environments
![image](https://github.com/fabian-hiller/valibot/assets/119697239/02d7791d-f61f-466b-9a09-c5c24a34429e)
![image](https://github.com/fabian-hiller/valibot/assets/119697239/d7472c89-8ccf-4b2e-9c3e-65a507f295dd)

**Comment by fabian-hiller** [comment]
This is a good idea. The only drawback might be that it is not clear whether the input was the string "Invalid Date" or an invalid date object, but it is probably better than the current solution.

**Comment by HugeLetters** [comment]
We could use quotes which are not used for strings then :)
If string are display with `"` then we might use `` ` `` or `'`

**Comment by fabian-hiller** [comment]
I am not sure I want to introduce a new syntax just for one case. I recommend going with "Invalid Date" until we find a better solution.

**Comment by fabian-hiller** [comment]
Valibot v0.33.1 is available 🎉

**Comment by HugeLetters** [comment]
great, thanks!
