### ISSUE TITLE
issue - recursive schema seems to produce incomplete Issues

### ISSUE THREAD

**Issue by cateland** [fabian-hiller/valibot#724]
Minimal reproduction case found here > https://playcode.io/1940581

Using recursive Schema i expected to have clear issues generated with a path. Alas it is undefined in the linked case.
It seems also to impede the `flatten` function to produce meaningful resulsts.

**Comment by fabian-hiller** [comment]
I recommend to use `variant` instead of `union`. Checkout [this playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAIg2QBtgAjCGQgbgCh6YBPMAUzgEkAJaYALwgA7GGQAyyZhACu8ALxwA3vThwW7AFxFeUAcNGkJU2XRVw2pNiDYjUWgIJQokgDycjMmAD4GAX0bqHJwAamywwADG4pKecArKqoFahKHhUYYxJgyqFlY2MHZwjs7Mbh6yPvT+TKxB5fJcOnoi0cbwAD5cqTCRrZ4M9BHCqPA8fIItGW0AyhEAFlbIcZgAdBAUAFZsETAAFAlqtVoYK+QwYWS7hE0TBvWEAJQANGa51rbHp8j8zLu7D3EvKtkE5JLt3JkYLMFiBkA9nlUHgMhkIRl0wj10vVoYtlid1lsdvszElVmcLqQrt1elNPI8XjlLO8Cp9SN9fv9AcDQb8ITN5ot4S9fEjGCi0XzPDjYZ8AOI2MKRaXIMqQoEKE4kXTIES7ADkgT1TzgAG0zGNdLc+rJlQz0WlrVCBbCXgBdUWDYbwKBsVDSUgNE6oZDYNgABRBqDY4OxzuQxsUh00RAAKgBRaYpwjGt75QomxS+V1wEUDYDYOC7ACEPr9AZWfoiEV9qABB3FEEsKzCeCgu1r-pgK2AqD9vtFqg7XZ70F2J2wbJg5yE-d9g+Ho+k49F-iAA) and have a look at [this guide](https://valibot.dev/guides/unions/) for more details.

**Comment by cateland** [comment]
@fabian-hiller thanks a lot will keep you posted !

**Comment by cateland** [comment]
Everything is awesome thank you, missed the use of variant for this case.
