### ISSUE TITLE
"Cannot read properties of null" when using trim with nullish

### ISSUE THREAD

**Issue by samuba** [fabian-hiller/valibot#770]
This code throws `TypeError: Cannot read properties of null (reading 'trim')`

```ts
const Schema = v.object({
  foo: v.pipe(v.nullish(v.string()), v.trim()),
});

const result = v.safeParse(Schema, {
  foo: null,
});
```

Is there any reason we're not using safe navigation operator when applying transforms?
e.g. 
```ts
dataset.value = dataset.value?.trim();
```

**Comment by fabian-hiller** [comment]
This is related to #669. There should be a TypeScript warning to prevent this from happening when using TypeScript.

The fix is to wrap `nullish` around `pipe`. This way only `strings` will pass through the pipeline. See [this playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6CBQBWfJjAAUAb3pwcECAC5xrAK6lyqHvIxiwwMH2NiOUYKwDm8gJQAacTFshnT1-QC+TgzMbBxwUHyoevCiJqjI2HwACshQqJbc-IJuyqrY6lq6+i7+gYws7BCkfGKkEI7hkaQwpUA).

```ts
import * as v from 'valibot';

const Schema = v.object({
  foo: v.nullish(v.pipe(v.string(), v.trim())),
});
``

**Comment by samuba** [comment]
I see, thank you. Definitely worth to add this to the documentation.

**Comment by fabian-hiller** [comment]
I think the current approach is simple and clear. You can't trim `null`, but you can trim `string`. So it makes sense to only `pipe` the `string` schema. Changing this behavior would, in my opinion, make it less clear how to use our API. However, I appreciate your feedback and will look into it again when I take a closer look at #669.

**Comment by fabian-hiller** [comment]
There will now be a TS warning in the latest version if our API is used incorrectly.
