### ISSUE TITLE
Minify dist files with tsup

### ISSUE THREAD

**Issue by welpie21** [fabian-hiller/valibot#79]
I have forked your project to have a look and I noticed a small thing. The `tsup` config file has no minify property. Was it intended to not put it in there?

Not sure how it will effect bundle size in general and I would like to learn more.

I've just in case put a comparison between disabling and enabling.

When `minify` is set to `false` the javascript bundle size exceeds to:
- cjs: 98.04kb
- esm: 92.87kb

When `minify` is set to `true` the javascript bundle size exceeds to:
- cjs: 31.94kb
- esm: 31.36kb

I can make a PR if you wish to implement or you see don't have to.

**Comment by fabian-hiller** [comment]
This is intended. Valibot is a library that is mostly used in combination with other frameworks and libraries. The result of minification is better if it is done only in the final build step of an application.

A change in our tsup config does not affect the bundle size on bundlephobia, bundlejs and pkg-size, because these tools minify the library independently.
