### ISSUE TITLE
Using other keys for validation?

### ISSUE THREAD

**Issue by hongkongkiwi** [fabian-hiller/valibot#931]
Using valibot, how can I validate against other fields in the schema?

For example, I have a schema like this:
```
  v.object({  
    saveToS3: v.optional(v.boolean(), false),
    s3Config: v.optional(v.object({
      bucket: v.string(),
      region: v.optional(v.string(), 'us-east-1'),
      key: v.optional(v.string()),
    })),
  }),
```

I would like to validate that if saveToS3 is true then s3Config must be present and contain the bucket key.

I know that we can use custom validation methods, but I couldn't quite see how I would access other keys within that method.

**Comment by ivanbarlog** [comment]
You should use [`v.variant()`](https://valibot.dev/api/variant/) in order to achieve this.

Here is the [link for the playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XlSYAsBTEZHAC8mAHQkowZKxgAKQqmQZeAFQgBlAMyEANHADa9OGIgUAVryZyA3keNxFytVoBcY8jF5QysmFACuvACUOnbGqJoAwmzYwADmbhiiphZWsrb29hT+TADWvDCJohySrHGyIWH2ULxxwGxFEGAw9aw+SSXAZRV6hP6oALS8aDADAIyElZnG+QCejc2t7cV+XeVBU-YAvps7ocZJKZY2VY6qGppFHl4+2GSowftwe-QAukEMzGwccDWo-qR4CIOshsLwAArIKAPWRcPgCPTWBxKc6uHD3XjPD70YDYOCyP4AmDFHJMXioVBBOAZOAsdgQUi8USkCDlQmA5L+GBgLnYrZwXikB7Uux01AMpkstnkomiYAUwKUhhbehAA) with an example.
