### ISSUE TITLE
Input type should be optional after withDefault

### ISSUE THREAD

**Issue by ooga** [fabian-hiller/valibot#96]
When using `withDefault()`, the inferred input type of the defaulted value should be optional

<img width="948" alt="image" src="https://github.com/fabian-hiller/valibot/assets/3911114/f8183f8a-ad92-4669-aebd-c02399707415">

Maybe wrap returned schema with `optional()` ?

**Comment by fabian-hiller** [comment]
That is correct. I will improve that. Thanks for the hint!

**Comment by ooga** [comment]
What do you think about adding default value as parameter of `optional()` ?
It will be more explicit when reading schema

**Comment by fabian-hiller** [comment]
Thanks for the idea. I'll give it some thought.

**Comment by fabian-hiller** [comment]
I am not sure anymore if the input type should be `undefined`. It depends on how `withDefault` and the input type is interpreted. If the passed value in `withDefault` is the input in case of `undefined`, then the input is not `undefined`. I hope you understand what I mean.

The input type defines the initial data set that runs through the schema. When using `withDefault`, this type/value is no longer `undefined`. As the documentation describes, the input type can differ from the output using `transform`.

If you want the input type to be `undefined` as well, you can pass `optional(string())` as the first parameter instead of `string()`. It would then be necessary that `withDefault` changes the output type to `string` since it can no longer be `undefined`.

Please let me know your thoughts on this. I have not yet made a decision in this regard.

**Comment by ooga** [comment]
> The input type defines the initial data set that runs through the schema. When using `withDefault`, this type/value is no longer `undefined`.

From my point of view, using `withDefault` creates a new schema, and we need to reflect the input of this newly created schema. 
The type/value that is no longer `undefined` is not the input anymore. 
The `withDefault` is like a `transform` but acting before the validation.

**Comment by fabian-hiller** [comment]
This procedure, however, would have the consequence that also, in the [pipeline](https://valibot.dev/guides/pipelines/), the data type is optionally `undefined`, whereby almost none of the validation functions, like `minLength` and `regex`, would work anymore.

**Comment by ooga** [comment]
The input of the pipeline and the "main" input are not the same, so the type shouldn't be the same. It might be challenging, but that is how it should work in my opinion

**Comment by fabian-hiller** [comment]
Will think about it. Thank you for your feedback.

**Comment by octet-stream** [comment]
I probably have similar issue, except that in my case after `withDefault()` output type becomes `number | undefined` if I use `optional()` on one of the types. Here's the example: https://stackblitz.com/edit/typescript-rgjtfe?file=ZodPort.ts,ValibotPort.ts

Zod gives me `number | string | undefined` as input and `number` as output. Which is what I want to achieve. At the same time, with valibot I get `number | string | undefined` as input and `number | undefined` as output.

**Comment by fabian-hiller** [comment]
Thanks for the tip. I will investigate this in detail soon and find a solution.

**Comment by fabian-hiller** [comment]
I deprecated `withDefault` and revised `optional`, `nullable` and `nullish`. With the next version the changes will go live.

**Comment by fabian-hiller** [comment]
v0.15.0 is now available.

**Comment by fabian-hiller** [comment]
The recommended way is to use `optional`, `nullable` or `nullish`:

```ts
const Schema = optional(string(), 'default_value');
```

**Comment by xia0pin9** [comment]
it seems with `const Schema = optional(coerce(number(), Number), 100);` and input of "", I am getting 0 output instead of the default value

**Comment by fabian-hiller** [comment]
The default value for `optional` is only applied if `undefined` is passed.
